function method_list = setup_methods(ch_names, trial_num, it_num, is_planar)
    % for Johnny_total_comparison
    accur_mean_r = zeros(it_num, 1);  accur_mean_t = zeros(it_num, 1);
    accur_med_r = zeros(it_num, 1);  accur_med_t = zeros(it_num, 1);
    efficiency_ratio = zeros(it_num, 1);
    
    % compared methods    
    A= zeros(it_num, 1);
    B= zeros(trial_num, it_num);
    met_type = {1,1,1,3,3,3,4,2,2,2,1,...
                3,3,3,1,3,2,2,4,...
                1,1,1,...
                2,2,2,2,2};
    name= {'Mirzaei','RPnL', 'Pluecker', 'EPnP\_GN', 'EPnP\_GNN', 'OPnP', 'OPnP*', 'EPnPL', 'OPnPL', 'DLT', 'OPnP\_naive',...
            'LHM', 'RPnP', 'DLS', 'SRPnL','EOPnP','EOPnPL','EOPnPL-Pm','EOPnP*',...
            'Ansar','ASPnL','LPnL\_Bar\_ENull',...
            'EOPnPL-BJ-0','EOPnPL-BJ-1','EOPnPL-BJ-2','EOPnPL-BJ-3','EOPnPL-BJ-4'};
    f= {   @Mirzaei, @PNLWrapper, @plueckerWrapper, @EPnP_GNN, @EPnP_GNN, @OPnP, @OPnP, @EPnPLS_GN, @OPnPL, @DLT, @OPnP_E,...
            @LHM, @RPnP, @dls_pnp_all,@SRPnL,@EOPnP,@EOPnPL,@EOPnPL_Pm,@EOPnP ,...
            @Ansar,@ASPnL,@LPnL_Bar_ENull,...%@AlgLS_lx   @Mirzaei  @NLL_lx
            @EOPnPL_BJ,@EOPnPL_BJ,@EOPnPL_BJ,@EOPnPL_BJ,@EOPnPL_BJ};
    marker= { '^', 'v', 's', 'o', 'x', 'x', 'none', '+','o', '<','v',...
                '+', 'd', '^', '*','h','x','x','^',...
               's', 'x','^',...
               '*','*','*','*','*'};
    color= {'r','g','b',[1,0.502,0],'m','b','k',[0  0.6   0.1],'k',[1,0.502,0],'b',...
            'm','y','c',[1,0.502,0],'r', 'm',[1,0.502,0.3],[1,0.502,0.3],...
            'b',[0,1,1],'r',...
            'r',[252,170,103]./255,[84,134,135]./255,'b',[189,30,30]./255};
    markerfacecolor=  color;%{'r','g','n','m','n','n','r','r','g'};
    linestyle= {'-','--',':','-','-','-',':','-','-',':','-',...
                '-','-','-','-','-','-','-','-',...
                '-','-',':',...
                ':',':',':',':',':'};  
    min_pt_num = {0,0,0,6,6,3,3,3,3,6,3,...
                    3,3,3,0,3,0,3,3,...
                   0,0,0,...
                   3,3,3,3,3 };
    min_ln_num = {6,6,10,0,0,0,3,3,3,6,3,...
                    0,0,0,6,0,3,3,3,...
                   6,6,6,...
                   3,3,3,3,3 };
    
               
               
    name_planar = {'Mirzaei','RPnL', 'EPnP\_Planar\_GN', 'OPnP', 'OPnP*', 'EPnPL\_Planar', 'OPnPL', 'DLT\_Planar',...
                    'LHM', 'RPnP', 'DLS', 'SRPnL','EOPnP','EOPnPL','EOPnP*',...
                    'Ansar','ASPnL','LPnL\_Bar\_ENull'};
    f_planar = {   @Mirzaei, @PNLWrapper, @EPnP_planar_GN, @OPnP, @OPnP, @EPnPLS_Planar_GN, @OPnPL, @DLT_planar,...
                    @LHM, @RPnP, @dls_pnp_all,@SRPnL,@EOPnP,@EOPnPL,@EOPnP,...
                   @Ansar,@ASPnL,@LPnL_Bar_ENull };%@AlgLS_lx  @NLL_lx   @Mirzaei
    met_type_planar = {1,1,3,3,4,2,2,2,...
                        3,3,3,1,3,2,4,...
                       1,1,1 };
    marker_planar = { '^', 'v',  'o',  'x', 'none', '+','o', '<',...
                         '+', 'd', '^', '*','h','x','^',...
                        's',  'x', '^' };
    color_planar = {'r','g',[1,0.502,0],'b','k',[0  0.6   0.1],'k',[1,0.502,0],...
                        'm','y','c',[1,0.502,0],'r', 'm',[1,0.502,0.3],...
                       'b',[0,1,1],'r'};
    markerfacecolor_planar =  color_planar;%{'r','g','n','m','n','n','r','r','g'};
    linestyle_planar = {'-','--','-','-',':','-','-',':',...
                           '-','-','-','-','-','-','-',...
                           '-','-',':'};
    min_pt_num_planar = {0,0,0,0,3,6,3,6,...
                           3,3,3,0,3,0,3,...
                           0,0,0};
    min_ln_num_planar = {6,6,0,0,3,6,3,6,...
                           0,0,0,6,0,3,3,...
                          6,6,6};
    
    if (is_planar)
        f = f_planar;
        name = name_planar;
        met_type = met_type_planar;
        marker = marker_planar;
        color = color_planar;
        markerfacecolor = markerfacecolor_planar;
        linestyle = linestyle_planar;
        min_pt_num = min_pt_num_planar;
        min_ln_num = min_ln_num_planar;
    end
    
    

    flags = zeros(length(name), 1);
    inds = [];
    for i = 1:length(ch_names)
        ind = find(strcmp(name, ch_names{i}));
        inds = [inds; ind];
    end
    
    marker = marker(inds);
    color = color(inds);
    markerfacecolor = markerfacecolor(inds);
    linestyle = linestyle(inds);
    name = name(inds);
    f = f(inds);
    met_type = met_type(inds);
    min_pt_num = min_pt_num(inds);
    min_ln_num = min_ln_num(inds);
    
    method_list= struct('name', name, 'f', f, 'mean_r', A, 'mean_t', A, 'mean_foc', A, 'mean_reproj', A, ...
        'med_r', A, 'med_t', A, 'med_foc', A, 'med_reproj', A, 'r', B, 't', B,...
        'foc', B, 'reproj', B, 'marker', marker, 'color', color, ...
        'markerfacecolor', markerfacecolor, 'linestyle', linestyle,'met_type',met_type, 'min_pt_num', min_pt_num, 'min_ln_num', min_ln_num,...
        'accur_mean_r', accur_mean_r, 'accur_mean_t', accur_mean_t,...
        'accur_med_r', accur_med_r, 'accur_med_t', accur_med_t,'efficiency_ratio', efficiency_ratio);

end